#!/usr/bin/env node
/**
 * Generates the TypeScript data model from the vendored DATEX II JSON Schemas.
 *
 * Handles both dialects the DATEX II tooling emits: draft-04 with `definitions`
 * and draft 2020-12 with `$defs`.
 *
 * Everything under src/generated/ is produced by this script - never edit it by
 * hand. Point SCHEMA_DIR at another DATEX II schema set (e.g. a full v3.7
 * download from https://docs.datex2.eu/downloads/) and re-run to retarget the
 * library at that model.
 *
 *   node scripts/generate.mjs [schemaDir] [outDir]
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const SCHEMA_DIR = resolve(process.argv[2] ?? join(ROOT, 'schemas', 'datex2-v3.7'));
const OUT_DIR = resolve(process.argv[3] ?? join(ROOT, 'src', 'generated'));

const FILE_PREFIX = 'DATEXII_3_';
const BANNER = `// AUTO-GENERATED by scripts/generate.mjs - do not edit.
// Source: DATEX II v3 JSON Schemas in schemas/datex2-v3.7/.
/* eslint-disable */
`;

/* -------------------------------------------------------------------------- */
/* 1. Load schemas                                                             */
/* -------------------------------------------------------------------------- */

/** DATEX II schemas ship as draft-04 (`definitions`) or 2020-12 (`$defs`). */
const defsOf = (doc) => doc.$defs ?? doc.definitions ?? {};

const files = readdirSync(SCHEMA_DIR)
  .filter((f) => f.endsWith('.json') && f.startsWith(FILE_PREFIX))
  .sort();

if (files.length === 0) {
  throw new Error(`No ${FILE_PREFIX}*.json schemas found in ${SCHEMA_DIR}`);
}

/** namespace -> raw schema document */
const docs = new Map();
/** file name -> namespace */
const nsByFile = new Map();

for (const file of files) {
  const ns = basename(file, '.json').slice(FILE_PREFIX.length);
  docs.set(ns, JSON.parse(readFileSync(join(SCHEMA_DIR, file), 'utf8')));
  nsByFile.set(file, ns);
}

/* -------------------------------------------------------------------------- */
/* 2. Registry + TypeScript names                                              */
/* -------------------------------------------------------------------------- */

/** "ns:local" -> { ns, local, raw } */
const registry = new Map();
const localCount = new Map();

for (const [ns, doc] of docs) {
  for (const [local, raw] of Object.entries(defsOf(doc))) {
    registry.set(`${ns}:${local}`, { ns, local, raw });
    localCount.set(local, (localCount.get(local) ?? 0) + 1);
  }
}

/** DATEX II class names are unique model-wide; namespace-qualify only on clash. */
function tsNameOf(ns, local) {
  return (localCount.get(local) ?? 0) > 1 ? `${ns}${local}` : local;
}

for (const entry of registry.values()) {
  entry.ts = tsNameOf(entry.ns, entry.local);
}

/** "#/$defs/X" or "DATEXII_3_Ns.json#/definitions/X" -> registry key */
function refKey(ref, currentNs) {
  const [filePart, pointer] = ref.split('#');
  const local = pointer.replace(/^\/(?:\$defs|definitions)\//, '');
  const ns = filePart ? nsByFile.get(filePart) : currentNs;
  if (!ns) throw new Error(`Unresolvable $ref target file: ${ref}`);
  const key = `${ns}:${local}`;
  if (!registry.has(key)) throw new Error(`Dangling $ref: ${ref}`);
  return key;
}

const lookup = (key) => registry.get(key);

/* -------------------------------------------------------------------------- */
/* 3. Classify definitions                                                     */
/* -------------------------------------------------------------------------- */

const JSON_SCALARS = new Set(['string', 'number', 'integer', 'boolean']);

function classify(entry) {
  const { raw } = entry;
  if (Array.isArray(raw.enum)) return 'enum';
  if (raw.type === 'object' || raw.properties) {
    if (raw.additionalProperties === true) return 'extension';
    const props = raw.properties ?? {};
    const names = Object.keys(props);
    if (names.includes('value') && names.every((n) => n === 'value' || n === 'extendedValueG')) {
      return 'enumWrapper';
    }
    if (entry.local.endsWith('G') && names.some((n) => isClassRef(props[n], entry.ns))) {
      return 'choice';
    }
    return 'object';
  }
  return 'scalar';
}

/** true when the property is a direct $ref to a definition that models a class */
function isClassRef(prop, ns) {
  if (!prop || typeof prop.$ref !== 'string') return false;
  const target = lookup(refKey(prop.$ref, ns));
  if (!target) return false;
  const raw = target.raw;
  if (Array.isArray(raw.enum)) return false;
  if (raw.type !== 'object' && !raw.properties) return false;
  if (raw.additionalProperties === true) return false;
  const names = Object.keys(raw.properties ?? {});
  return !(names.includes('value') && names.every((n) => n === 'value' || n === 'extendedValueG'));
}

for (const entry of registry.values()) entry.kind = classify(entry);

/* -------------------------------------------------------------------------- */
/* 4. Property model                                                           */
/* -------------------------------------------------------------------------- */

/** Strip the DATEX II "G" technical marker unless that would shadow a sibling. */
function friendlyPropName(wire, siblings) {
  if (wire.length > 1 && wire.endsWith('G')) {
    const stripped = wire.slice(0, -1);
    if (!siblings.has(stripped)) return stripped;
  }
  return wire;
}

/** Describe one JSON Schema property as { type, array, inline } */
function describeProp(schema, ns) {
  if (schema.type === 'array') {
    const item = describeProp(schema.items ?? {}, ns);
    return {
      ...item,
      array: true,
      minItems: schema.minItems,
      maxItems: schema.maxItems,
    };
  }
  if (typeof schema.$ref === 'string') {
    const target = lookup(refKey(schema.$ref, ns));
    return { array: false, ref: `${target.ns}:${target.local}`, ts: target.ts };
  }
  if (JSON_SCALARS.has(schema.type)) {
    return {
      array: false,
      inline: schema.type,
      format: schema.format,
      enum: schema.enum,
      pattern: schema.pattern,
    };
  }
  return { array: false, inline: 'unknown' };
}

function buildProps(entry) {
  const props = entry.raw.properties ?? {};
  const required = new Set(entry.raw.required ?? []);
  const siblings = new Set(Object.keys(props));
  const attrs = [];
  const choices = [];

  for (const [wire, schema] of Object.entries(props)) {
    const info = describeProp(schema, entry.ns);
    if (entry.kind === 'choice' && !info.array && info.ref && isClassRef(schema, entry.ns)) {
      choices.push({ wire, ref: info.ref, ts: info.ts });
      continue;
    }
    attrs.push({
      wire,
      friendly: friendlyPropName(wire, siblings),
      required: required.has(wire),
      ...info,
    });
  }
  entry.attrs = attrs;
  entry.choices = choices;
}

for (const entry of registry.values()) {
  if (entry.kind === 'object' || entry.kind === 'choice' || entry.kind === 'enumWrapper') {
    buildProps(entry);
  }
}

/* Guard the flattened friendly representation of choices against collisions. */
for (const entry of registry.values()) {
  if (entry.kind !== 'choice') continue;
  const attrNames = new Set(entry.attrs.map((a) => a.friendly));
  if (attrNames.has('_type')) {
    throw new Error(`${entry.ts}: choice attribute named "_type" collides with the discriminator`);
  }
  for (const choice of entry.choices) {
    const member = lookup(choice.ref);
    for (const p of member.attrs ?? []) {
      if (attrNames.has(p.friendly)) {
        throw new Error(
          `${entry.ts}: flattening ${member.ts} collides on property "${p.friendly}"`,
        );
      }
    }
  }
}

/* -------------------------------------------------------------------------- */
/* 5. Scalar resolution                                                        */
/* -------------------------------------------------------------------------- */

const CONSTRAINT_KEYS = [
  'minimum',
  'maximum',
  'exclusiveMinimum',
  'exclusiveMaximum',
  'minLength',
  'maxLength',
  'pattern',
  'format',
];

function scalarInfo(entry) {
  const chain = [];
  let cur = entry;
  const constraints = {};
  while (cur) {
    for (const k of CONSTRAINT_KEYS) {
      if (cur.raw[k] !== undefined && constraints[k] === undefined) constraints[k] = cur.raw[k];
    }
    if (typeof cur.raw.$ref === 'string') {
      const next = lookup(refKey(cur.raw.$ref, cur.ns));
      chain.push(next.ts);
      cur = next;
      continue;
    }
    return { json: cur.raw.type ?? 'unknown', base: chain[0], constraints };
  }
  return { json: 'unknown', constraints };
}

for (const entry of registry.values()) {
  if (entry.kind === 'scalar') entry.scalar = scalarInfo(entry);
}

/* -------------------------------------------------------------------------- */
/* 6. Emit helpers                                                             */
/* -------------------------------------------------------------------------- */

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const key = (k) => (IDENT.test(k) ? k : JSON.stringify(k));
const lit = (v) => JSON.stringify(v);

const jsonToTs = (t) =>
  t === 'integer' || t === 'number' ? 'number' : t === 'boolean' ? 'boolean' : t === 'string' ? 'string' : 'unknown';

const cleanDoc = (text) => String(text).replace(/\s+/g, ' ').replace(/\*\//g, '*\\/').trim();

function docComment(entry, extra = []) {
  const lines = [`${entry.ns} :: ${entry.local}`, ...extra];
  const description = entry.raw.description ? cleanDoc(entry.raw.description) : '';
  const head = `/** ${lines.join(' - ')} */`;
  return description ? `/**\n * ${lines.join(' - ')}\n *\n * ${description}\n */` : head;
}

/** wire TypeScript type for a property */
function wireType(p) {
  let t;
  if (p.ref) t = lookup(p.ref).ts;
  else if (p.enum) t = p.enum.map(lit).join(' | ');
  else t = jsonToTs(p.inline);
  return p.array ? `${t}[]` : t;
}

/** friendly TypeScript type for a property */
function friendlyType(p) {
  let t;
  if (p.ref) {
    const target = lookup(p.ref);
    t = target.kind === 'scalar' || target.kind === 'enum' ? target.ts : target.ts;
  } else if (p.enum) {
    t = p.enum.map(lit).join(' | ');
  } else {
    t = jsonToTs(p.inline);
  }
  if (!p.array) return t;
  // A single value is accepted wherever a list is expected - toWire() lifts it.
  return `${t}[]`;
}

const sorted = [...registry.values()].sort((a, b) => (a.ts < b.ts ? -1 : a.ts > b.ts ? 1 : 0));

/* -------------------------------------------------------------------------- */
/* 7. enums.ts                                                                 */
/* -------------------------------------------------------------------------- */

function emitEnums() {
  const out = [BANNER];
  out.push(`type EnumObject<T extends readonly string[]> = { readonly [K in T[number]]: K };`);
  out.push(`const enumOf = <T extends readonly string[]>(values: T): EnumObject<T> => {`);
  out.push(`  const out = {} as Record<string, string>;`);
  out.push(`  for (const value of values) out[value] = value;`);
  out.push(`  return out as EnumObject<T>;`);
  out.push(`};`);
  out.push('');
  for (const e of sorted) {
    if (e.kind !== 'enum') continue;
    out.push(docComment(e, ['allowed values']));
    out.push(`export const ${e.ts}Values = [${e.raw.enum.map(lit).join(', ')}] as const;`);
    out.push(docComment(e));
    out.push(`export type ${e.ts} = (typeof ${e.ts}Values)[number];`);
    out.push(`export const ${e.ts} = enumOf(${e.ts}Values);`);
    out.push('');
  }
  return out.join('\n');
}

/* -------------------------------------------------------------------------- */
/* 8. wire.ts (types.ts)                                                       */
/* -------------------------------------------------------------------------- */

function emitWire() {
  const enumNames = sorted.filter((e) => e.kind === 'enum').map((e) => e.ts);
  const out = [BANNER];
  out.push(`import type {\n${enumNames.map((n) => `  ${n},`).join('\n')}\n} from './enums.js';`);
  out.push(`export type {\n${enumNames.map((n) => `  ${n},`).join('\n')}\n} from './enums.js';`);
  out.push('');

  for (const e of sorted) {
    switch (e.kind) {
      case 'enum':
        break;
      case 'scalar': {
        out.push(docComment(e, [describeConstraints(e.scalar.constraints)].filter(Boolean)));
        out.push(`export type ${e.ts} = ${e.scalar.base ?? jsonToTs(e.scalar.json)};`);
        out.push('');
        break;
      }
      case 'extension': {
        out.push(docComment(e, ['open extension container']));
        out.push(`export interface ${e.ts} {`);
        for (const [prop, schema] of Object.entries(e.raw.properties ?? {})) {
          const p = describeProp(schema, e.ns);
          out.push(`  ${key(prop)}?: ${wireType(p)};`);
        }
        out.push(`  [extension: string]: unknown;`);
        out.push(`}`);
        out.push('');
        break;
      }
      case 'enumWrapper':
      case 'object': {
        out.push(docComment(e));
        out.push(`export interface ${e.ts} {`);
        for (const p of e.attrs) {
          out.push(`  ${key(p.wire)}${p.required ? '' : '?'}: ${wireType(p)};`);
        }
        out.push(`}`);
        out.push('');
        break;
      }
      case 'choice': {
        out.push(docComment(e, ['substitution group - exactly one member is set']));
        out.push(`export interface ${e.ts} {`);
        for (const p of e.attrs) {
          out.push(`  ${key(p.wire)}${p.required ? '' : '?'}: ${wireType(p)};`);
        }
        for (const c of e.choices) out.push(`  ${key(c.wire)}?: ${c.ts};`);
        out.push(`}`);
        out.push('');
        break;
      }
    }
  }
  return out.join('\n');
}

function describeConstraints(c) {
  const parts = [];
  if (c.format) parts.push(`format ${c.format}`);
  if (c.minimum !== undefined) parts.push(`min ${c.minimum}`);
  if (c.maximum !== undefined) parts.push(`max ${c.maximum}`);
  if (c.exclusiveMinimum !== undefined) parts.push(`> ${c.exclusiveMinimum}`);
  if (c.exclusiveMaximum !== undefined) parts.push(`< ${c.exclusiveMaximum}`);
  if (c.maxLength !== undefined) parts.push(`maxLength ${c.maxLength}`);
  if (c.pattern) parts.push('pattern constrained');
  return parts.join(', ');
}

/* -------------------------------------------------------------------------- */
/* 9. friendly.ts                                                              */
/* -------------------------------------------------------------------------- */

function emitFriendly() {
  const enumNames = sorted.filter((e) => e.kind === 'enum').map((e) => e.ts);
  const out = [BANNER];
  out.push(`import type {\n${enumNames.map((n) => `  ${n},`).join('\n')}\n} from './enums.js';`);
  out.push(`export type {\n${enumNames.map((n) => `  ${n},`).join('\n')}\n} from './enums.js';`);
  out.push('');

  for (const e of sorted) {
    switch (e.kind) {
      case 'enum':
        break;
      case 'scalar': {
        out.push(docComment(e, [describeConstraints(e.scalar.constraints)].filter(Boolean)));
        out.push(`export type ${e.ts} = ${e.scalar.base ?? jsonToTs(e.scalar.json)};`);
        out.push('');
        break;
      }
      case 'extension': {
        out.push(docComment(e, ['open extension container']));
        out.push(`export interface ${e.ts} {`);
        for (const [prop, schema] of Object.entries(e.raw.properties ?? {})) {
          const p = describeProp(schema, e.ns);
          out.push(`  ${key(prop)}?: ${friendlyType(p)};`);
        }
        out.push(`  [extension: string]: unknown;`);
        out.push(`}`);
        out.push('');
        break;
      }
      case 'enumWrapper': {
        const valueProp = e.attrs.find((p) => p.wire === 'value');
        const extProp = e.attrs.find((p) => p.wire === 'extendedValueG');
        const valueTs = valueProp ? friendlyType(valueProp) : 'string';
        const extTs = extProp ? friendlyType(extProp) : 'string';
        out.push(docComment(e, ['plain value, or an object carrying an extended value']));
        out.push(
          `export type ${e.ts} = ${valueTs} | { value: ${valueTs}; extendedValue?: ${extTs} };`,
        );
        out.push('');
        break;
      }
      case 'object': {
        out.push(docComment(e));
        out.push(`export interface ${e.ts} {`);
        for (const p of e.attrs) {
          out.push(`  ${key(p.friendly)}${p.required ? '' : '?'}: ${friendlyType(p)};`);
        }
        out.push(`}`);
        out.push('');
        break;
      }
      case 'choice': {
        const attrLines = e.attrs.map(
          (p) => `  ${key(p.friendly)}${p.required ? '' : '?'}: ${friendlyType(p)};`,
        );
        const base = attrLines.length ? `{\n${attrLines.join('\n')}\n}` : null;
        const members = e.choices.map((c) => {
          const target = lookup(c.ref);
          return `({ _type: ${lit(target.ts)} } & ${target.ts})`;
        });
        const union = members.length ? members.join('\n  | ') : 'Record<string, never>';
        out.push(docComment(e, ['discriminated union - pick a member with _type']));
        if (base) {
          out.push(`export type ${e.ts} = ${base} & (\n  ${union}\n);`);
        } else {
          out.push(`export type ${e.ts} =\n  ${union};`);
        }
        out.push('');
        break;
      }
    }
  }
  return out.join('\n');
}

/* -------------------------------------------------------------------------- */
/* 10. metadata.ts                                                             */
/* -------------------------------------------------------------------------- */

function propMeta(p) {
  // `f` is omitted when it equals `w`; the runtime falls back to `w`.
  const m = p.friendly === p.wire ? { w: p.wire } : { w: p.wire, f: p.friendly };
  if (p.ref) m.t = lookup(p.ref).ts;
  else m.j = p.inline;
  if (p.array) m.a = true;
  if (p.required) m.r = true;
  if (p.minItems !== undefined) m.minItems = p.minItems;
  if (p.maxItems !== undefined) m.maxItems = p.maxItems;
  if (p.enum) m.values = p.enum;
  if (p.format) m.format = p.format;
  if (p.pattern) m.pattern = p.pattern;
  return m;
}

function emitMetadata() {
  const defs = {};
  for (const e of sorted) {
    const m = { ns: e.ns, name: e.local, kind: e.kind };
    switch (e.kind) {
      case 'enum':
        m.values = e.raw.enum;
        break;
      case 'scalar':
        m.json = e.scalar.json;
        if (e.scalar.base) m.base = e.scalar.base;
        if (Object.keys(e.scalar.constraints).length) m.constraints = e.scalar.constraints;
        break;
      case 'extension':
        m.open = true;
        m.props = Object.entries(e.raw.properties ?? {}).map(([wire, schema]) => {
          const p = describeProp(schema, e.ns);
          return propMeta({ wire, friendly: wire, ...p });
        });
        break;
      case 'enumWrapper':
      case 'object':
        m.props = e.attrs.map(propMeta);
        if (e.raw.additionalProperties !== false) m.open = true;
        break;
      case 'choice':
        m.props = e.attrs.map(propMeta);
        m.choices = e.choices.map((c) => ({ w: c.wire, t: lookup(c.ref).ts }));
        if (e.raw.additionalProperties !== false) m.open = true;
        break;
    }
    defs[e.ts] = m;
  }

  const roots = {};
  for (const [ns, doc] of docs) {
    if (!doc.properties) continue;
    for (const [prop, schema] of Object.entries(doc.properties)) {
      const p = describeProp(schema, ns);
      if (p.ref) roots[prop] = lookup(p.ref).ts;
    }
  }

  const payload = registry.get('Common:PayloadPublicationG');
  const defaults = {};
  for (const [k, v] of Object.entries(payload?.raw.properties ?? {})) {
    if (v.default !== undefined) defaults[k] = v.default;
  }

  const out = [BANNER];
  out.push(`import type { DefMeta } from '../runtime/meta-types.js';`);
  out.push('');
  out.push(`/** Namespaces present in the generated model. */`);
  out.push(`export const namespaces = ${lit([...docs.keys()])} as const;`);
  out.push(`export type Namespace = (typeof namespaces)[number];`);
  out.push('');
  out.push(`/** Schema-declared defaults for the payload publication envelope. */`);
  out.push(`export const payloadDefaults = ${JSON.stringify(defaults, null, 2)} as const;`);
  out.push('');
  out.push(`/** Top-level entry points declared by the schema documents. */`);
  out.push(`export const roots = ${JSON.stringify(roots, null, 2)} as const;`);
  out.push('');
  // One compact line per definition: small enough to ship, still diffable.
  const entries = Object.entries(defs)
    .map(([name, meta]) => `  ${key(name)}: ${JSON.stringify(meta)},`)
    .join('\n');
  out.push(`/** Runtime description of every definition, keyed by TypeScript name. */`);
  out.push(`export const defs = {\n${entries}\n} as unknown as Record<TypeName, DefMeta>;`);
  out.push('');
  out.push(`export type TypeName =\n${sorted.map((e) => `  | ${lit(e.ts)}`).join('\n')};`);
  out.push('');
  return out.join('\n');
}

/* -------------------------------------------------------------------------- */
/* 11. index + type registry                                                   */
/* -------------------------------------------------------------------------- */

function emitRegistryModule(kindLabel, moduleFile) {
  const named = sorted.filter((e) => e.kind !== 'enum');
  const out = [BANNER];
  out.push(`import type * as M from './${moduleFile}';`);
  out.push('');
  out.push(`/** Maps a DATEX II type name to its ${kindLabel} TypeScript type. */`);
  out.push(`export interface ${kindLabel === 'wire' ? 'WireTypes' : 'FriendlyTypes'} {`);
  for (const e of named) out.push(`  ${key(e.ts)}: M.${e.ts};`);
  out.push(`}`);
  out.push('');
  return out.join('\n');
}

function emitIndex() {
  return `${BANNER}
export * from './enums.js';
export * as wire from './wire.js';
export * as friendly from './friendly.js';
export { defs, roots, namespaces, payloadDefaults } from './metadata.js';
export type { TypeName, Namespace } from './metadata.js';
export type { WireTypes } from './wire-registry.js';
export type { FriendlyTypes } from './friendly-registry.js';
`;
}

/* -------------------------------------------------------------------------- */
/* 12. Write                                                                   */
/* -------------------------------------------------------------------------- */

mkdirSync(OUT_DIR, { recursive: true });
const outputs = {
  'enums.ts': emitEnums(),
  'wire.ts': emitWire(),
  'friendly.ts': emitFriendly(),
  'metadata.ts': emitMetadata(),
  'wire-registry.ts': emitRegistryModule('wire', 'wire.js'),
  'friendly-registry.ts': emitRegistryModule('friendly', 'friendly.js'),
  'index.ts': emitIndex(),
};
for (const [file, contents] of Object.entries(outputs)) {
  writeFileSync(join(OUT_DIR, file), contents.replace(/\n{3,}/g, '\n\n'));
}

const counts = {};
for (const e of registry.values()) counts[e.kind] = (counts[e.kind] ?? 0) + 1;
console.log(
  `generated ${registry.size} definitions from ${files.length} schema files ->  ${OUT_DIR}`,
);
console.log(
  Object.entries(counts)
    .sort()
    .map(([k, v]) => `  ${k}: ${v}`)
    .join('\n'),
);
